#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

usage() {
  echo "Usage: $0 \"tasks/active/TASK-001-sample.md\" [--root /path/to/SDD] [--dry-run]"
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
dry_run=0
task_path=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      root="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ -z "$task_path" ]]; then
        task_path="$1"
        shift
      else
        usage
        exit 1
      fi
      ;;
  esac
done

if [[ -z "$task_path" ]]; then
  usage
  exit 1
fi

active_dir="$root/tasks/active"
history_dir="$root/tasks/history"

if [[ "$task_path" = /* ]]; then
  source_path="$(cd "$(dirname "$task_path")" && pwd)/$(basename "$task_path")"
else
  source_path="$(cd "$(dirname "$root/$task_path")" && pwd)/$(basename "$task_path")"
fi

case "$source_path" in
  "$active_dir"/*) ;;
  *)
    echo "Only tasks under tasks/active/ can be archived: $source_path" >&2
    exit 1
    ;;
esac

destination_path="$history_dir/$(basename "$source_path")"

if [[ "$dry_run" -eq 1 ]]; then
  echo "[DRY RUN] Would archive $source_path -> $destination_path"
  exit 0
fi

mv "$source_path" "$destination_path"
echo "Archived $destination_path"
echo "Remember to update docs/process.md and docs/progress.md"
echo "Before the next session, leave a next-step entry: a new active task, a progress.md Next Options recommendation, or a full-profile backlog item."
