# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$TaskPath,

    [string]$Root = "",

    [switch]$DryRun
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$activeDir = Join-Path $Root "tasks\active"
$historyDir = Join-Path $Root "tasks\history"

if ([System.IO.Path]::IsPathRooted($TaskPath)) {
    $sourcePath = (Resolve-Path $TaskPath).Path
} else {
    $sourcePath = (Resolve-Path (Join-Path $Root $TaskPath)).Path
}

if (-not $sourcePath.StartsWith($activeDir, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Only tasks under tasks/active/ can be archived: $sourcePath"
}

$destinationPath = Join-Path $historyDir ([System.IO.Path]::GetFileName($sourcePath))

if ($DryRun) {
    Write-Host "[DRY RUN] Would archive $sourcePath -> $destinationPath"
    exit 0
}

Move-Item -LiteralPath $sourcePath -Destination $destinationPath -Force
Write-Host "Archived $destinationPath"
Write-Host "Remember to update docs/process.md and docs/progress.md"
Write-Host "Before the next session, leave a next-step entry: a new active task, a progress.md Next Options recommendation, or a full-profile backlog item."
