# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [string]$Root = "",

    [string]$CurrentTask = "",

    [string[]]$FilesTouched = @(),

    [string[]]$CommandsRun = @(),

    [string]$NextAction = "",

    [string]$CommitStatus = "",

    [string]$CommitMessage = "",

    [string]$UncommittedReason = "",

    [string]$Risk = ""
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$repoRoot = (Resolve-Path (Join-Path $Root "..")).Path
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
$branch = "unknown"
$gitRoot = ""
$gitScope = "."
try {
    $gitRoot = (git -C $repoRoot rev-parse --show-toplevel 2>$null).Trim()
    $gitRoot = ([System.IO.Path]::GetFullPath($gitRoot)).TrimEnd('\', '/')
    $repoRoot = ([System.IO.Path]::GetFullPath($repoRoot)).TrimEnd('\', '/')
    $Root = ([System.IO.Path]::GetFullPath($Root)).TrimEnd('\', '/')
    $branch = (git -C $gitRoot symbolic-ref --quiet --short HEAD 2>$null).Trim()
    if ([string]::IsNullOrWhiteSpace($branch)) {
        $branch = "unborn-or-detached"
    }
    if ($repoRoot -eq $gitRoot) {
        $gitScope = "."
    } elseif ($repoRoot.StartsWith("$gitRoot\", [System.StringComparison]::OrdinalIgnoreCase)) {
        $gitScope = $repoRoot.Substring($gitRoot.Length + 1)
    } else {
        $gitScope = "."
    }
} catch {
}

$gitStatus = @()
try {
    if ($gitRoot) {
        $gitStatus = @(git -C $gitRoot status --short -- $gitScope 2>$null)
    } else {
        $gitStatus = @(git -C $repoRoot status --short 2>$null)
    }
} catch {
}

Write-Output "## Session Handoff"
Write-Output ""
Write-Output "- [x] timestamp: $timestamp"
Write-Output "- [x] branch: $branch"
Write-Output "- [x] git scope: $gitScope"
Write-Output "- [ ] active task: $CurrentTask"
Write-Output "- [ ] files touched:"
if ($FilesTouched.Count -gt 0) {
    foreach ($item in $FilesTouched) {
        Write-Output "  - [ ] $item"
    }
} else {
    Write-Output "  - [ ] "
}

Write-Output "- [ ] commands run:"
if ($CommandsRun.Count -gt 0) {
    foreach ($item in $CommandsRun) {
        Write-Output "  - [ ] $item"
    }
} else {
    Write-Output "  - [ ] "
}

Write-Output "- [ ] unresolved risks: $Risk"
Write-Output "- [ ] commit status: $CommitStatus"
Write-Output "- [ ] uncommitted reason: $UncommittedReason"
Write-Output "- [ ] recommended commit message: $CommitMessage"
Write-Output "- [ ] recommended next step: $NextAction"
Write-Output "- [x] git status snapshot:"
if ($gitStatus.Count -gt 0) {
    foreach ($line in $gitStatus) {
        Write-Output "  - [x] $line"
    }
} else {
    Write-Output "  - [x] clean or unavailable"
}
