# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$Title,

    [string]$Root = "",

    [switch]$DryRun
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Content
    )

    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

$adrDir = Join-Path $Root "adr"
$recordsDir = Join-Path $adrDir "records"
$templatePath = Join-Path $Root "templates\adr\ADR-000-template.md"
$lockPath = Join-Path $recordsDir ".new-adr.lock"

if (-not (Test-Path -LiteralPath $templatePath)) {
    throw "ADR template not found: $templatePath"
}

$slug = ($Title.ToLowerInvariant() -replace "[^a-z0-9]+", "-" -replace "^-+|-+$", "")
if ([string]::IsNullOrWhiteSpace($slug)) {
    $slug = "decision"
}

while ($true) {
    try {
        New-Item -ItemType Directory -Path $lockPath -ErrorAction Stop | Out-Null
        break
    } catch {
        Start-Sleep -Milliseconds 100
    }
}

try {
    $existingIds = Get-ChildItem -Path $recordsDir -Filter "ADR-*.md" -File -ErrorAction SilentlyContinue | ForEach-Object {
        if ($_.BaseName -match "^ADR-(\d{3})(?:-|$)") {
            [int]$matches[1]
        }
    }

    $nextId = if ($existingIds) {
        ([int]($existingIds | Measure-Object -Maximum).Maximum) + 1
    } else {
        1
    }

    $id = "{0:D3}" -f $nextId
    $targetPath = Join-Path $recordsDir ("ADR-$id-$slug.md")

    $content = Get-Content -LiteralPath $templatePath -Raw
    $content = $content -replace "(?m)^# ADR-000: .+$", "# ADR-${id}: $Title"
    $content = $content -replace "(?m)^- proposed / accepted / superseded / deprecated$", "- proposed"

    if ($DryRun) {
        Write-Host "[DRY RUN] Would create $targetPath"
        Write-Output $content
        exit 0
    }

    Write-Utf8NoBom -Path $targetPath -Content $content
    Write-Host "Created $targetPath"
} finally {
    if (Test-Path -LiteralPath $lockPath) {
        Remove-Item -LiteralPath $lockPath -Force -ErrorAction SilentlyContinue
    }
}
