#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

usage() {
  echo "Usage: $0 \"Task title\" [--root /path/to/SDD] [--dry-run]"
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
dry_run=0
title=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      root="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ -z "$title" ]]; then
        title="$1"
        shift
      else
        usage
        exit 1
      fi
      ;;
  esac
done

if [[ -z "$title" ]]; then
  usage
  exit 1
fi

tasks_dir="$root/tasks"
active_dir="$tasks_dir/active"
template_path="$root/templates/tasks/TASK-template.md"
lock_dir="$active_dir/.new-task.lock"

if [[ ! -f "$template_path" ]]; then
  echo "Task template not found: $template_path" >&2
  exit 1
fi

slug="$(printf '%s' "$title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
if [[ -z "$slug" ]]; then
  slug="task"
fi

while ! mkdir "$lock_dir" 2>/dev/null; do
  sleep 0.1
done
trap 'rmdir "$lock_dir" 2>/dev/null || true' EXIT

max_id=0
shopt -s nullglob
for path in "$active_dir"/TASK-*.md; do
  name="$(basename "$path")"
  if [[ "$name" =~ ^TASK-([0-9]{3})(-.*)?\.md$ ]]; then
    current_id=$((10#${BASH_REMATCH[1]}))
    if (( current_id > max_id )); then
      max_id=$current_id
    fi
  fi
done

next_id=$((max_id + 1))
id="$(printf '%03d' "$next_id")"
target_path="$active_dir/TASK-$id-$slug.md"

rendered="$(awk -v id="$id" -v title="$title" '
NR == 1 { print "# TASK-" id ": " title; next }
$0 == "- draft / ready / in_progress / blocked / done" || $0 == "- [ ] draft / ready / in_progress / blocked / done" { print "- [ ] ready"; next }
{ print }
' "$template_path")"

if [[ "$dry_run" -eq 1 ]]; then
  echo "[DRY RUN] Would create $target_path"
  printf '%s\n' "$rendered"
  exit 0
fi

printf '%s\n' "$rendered" > "$target_path"
echo "Created $target_path"
