#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$root/.." && pwd)"
progress_path="$root/docs/progress.md"
process_path="$root/docs/process.md"
active_tasks_dir="$root/tasks/active"
history_tasks_dir="$root/tasks/history"
git_root="$(git -C "$repo_root" rev-parse --show-toplevel 2>/dev/null || true)"
workflow_profile="lite"
task_completion_git_mode="manual"
if [[ -f "$root/workflow-config.env" ]]; then
  while IFS='=' read -r key value; do
    value="${value%$'\r'}"
    case "$key" in
      WORKFLOW_PROFILE)
        workflow_profile="$value"
        ;;
      TASK_COMPLETION_GIT_MODE)
        task_completion_git_mode="$value"
        ;;
    esac
  done < "$root/workflow-config.env"
fi

section() {
  local heading="$1"
  awk -v target="## $heading" '
  $0 == target { capture=1; next }
  capture && /^## / { exit }
  capture { print }
  ' "$2"
}

timestamp="$(date '+%Y-%m-%d %H:%M:%S %z')"
if [[ -n "$git_root" ]]; then
  branch="$(git -C "$git_root" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'unborn-or-detached')"
  if [[ "$repo_root" == "$git_root" ]]; then
    git_scope="."
  elif [[ "$repo_root" == "$git_root/"* ]]; then
    git_scope="${repo_root#"$git_root"/}"
  else
    git_scope="."
  fi
  git_status="$(git -C "$git_root" status --short -- "$git_scope" 2>/dev/null || true)"
else
  branch="unknown"
  git_scope="."
  git_status=""
fi

printf '# Session Brief\n\n'
printf -- '- repo root: %s\n' "$repo_root"
printf -- '- workflow root: %s\n' "$root"
printf -- '- workflow profile: %s\n' "$workflow_profile"
printf -- '- task completion git mode: %s\n' "$task_completion_git_mode"
printf -- '- timestamp: %s\n' "$timestamp"
printf -- '- branch: %s\n' "$branch"
printf -- '- git scope: %s\n\n' "$git_scope"

for heading in "Macro Focus" "Rules of Archiving" "Recent History" "Pointers" "Current Focus" "Recent Archives" "Workflow Rules & Index" "Current Board" "Recently Completed" "Archiving Rules"; do
  if [[ -f "$process_path" ]]; then
    body="$(section "$heading" "$process_path")"
    if [[ -n "$body" ]]; then
      printf '## %s\n%s\n\n' "$heading" "$body"
    fi
  fi
done

for heading in "Current" "Recent Findings" "Session Handoff" "Concurrency" "Current Context" "Collaboration" "Current Summary" "Now" "Git Closure" "Next Options" "Next" "Parallel Work Summary" "Blockers"; do
  if [[ -f "$progress_path" ]]; then
    body="$(section "$heading" "$progress_path")"
    if [[ -n "$body" ]]; then
      printf '## %s\n%s\n\n' "$heading" "$body"
    fi
  fi
done

printf '## Git Status\n'
if [[ -n "$git_status" ]]; then
  while IFS= read -r line; do
    printf -- '- %s\n' "$line"
  done <<< "$git_status"
else
  printf -- '- clean or unavailable\n'
fi
printf '\n'

printf '## Recent Task Cards\n'
recent=0
shopt -s nullglob
task_paths=("$active_tasks_dir"/TASK-*.md)
if (( ${#task_paths[@]} > 0 )); then
  mapfile -t task_paths < <(ls -1t "${task_paths[@]}")
  for path in "${task_paths[@]}"; do
    printf -- '- %s\n' "$(basename "$path")"
    recent=$((recent + 1))
    if (( recent == 5 )); then
      break
    fi
  done
fi

if (( recent == 0 )); then
  printf -- '- no concrete task cards yet\n'
fi

printf '\n## Recent Subtasks\n'
recent=0
subtask_paths=("$active_tasks_dir"/SUBTASK-*.md)
if (( ${#subtask_paths[@]} > 0 )); then
  mapfile -t subtask_paths < <(ls -1t "${subtask_paths[@]}")
  for path in "${subtask_paths[@]}"; do
    printf -- '- %s\n' "$(basename "$path")"
    recent=$((recent + 1))
    if (( recent == 5 )); then
      break
    fi
  done
fi

if (( recent == 0 )); then
  printf -- '- no concrete subtasks yet\n'
fi

printf '\n## Recently Archived\n'
recent=0
history_paths=("$history_tasks_dir"/*.md)
if (( ${#history_paths[@]} > 0 )); then
  mapfile -t history_paths < <(ls -1t "${history_paths[@]}")
  for path in "${history_paths[@]}"; do
    printf -- '- %s\n' "$(basename "$path")"
    recent=$((recent + 1))
    if (( recent == 5 )); then
      break
    fi
  done
fi

if (( recent == 0 )); then
  printf -- '- no archived work yet\n'
fi
