# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [string]$Root = "",

    [string]$CurrentTask = "",

    [string[]]$FilesTouched = @(),

    [string[]]$CommandsRun = @(),

    [string]$NextAction = "",

    [string]$CommitStatus = "",

    [string]$CommitMessage = "",

    [string]$UncommittedReason = "",

    [string]$Risk = ""
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$hotStateBranchDir = "state/hot/branches"
$hotStateTaskDir = "state/hot/tasks"
if (Test-Path -LiteralPath (Join-Path $Root "workflow-config.env")) {
    foreach ($line in Get-Content -LiteralPath (Join-Path $Root "workflow-config.env")) {
        if ($line -match "^\s*HOT_STATE_BRANCH_DIR=(.+?)\s*$") {
            $hotStateBranchDir = $matches[1].Trim()
        }
        if ($line -match "^\s*HOT_STATE_TASK_DIR=(.+?)\s*$") {
            $hotStateTaskDir = $matches[1].Trim()
        }
    }
}

$repoRoot = (Resolve-Path (Join-Path $Root "..")).Path
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
$branch = "unknown"
$gitRoot = ""
$gitScope = "."
try {
    $gitRoot = (git -C $repoRoot rev-parse --show-toplevel 2>$null).Trim()
    $gitRoot = ([System.IO.Path]::GetFullPath($gitRoot)).TrimEnd('\', '/')
    $repoRoot = ([System.IO.Path]::GetFullPath($repoRoot)).TrimEnd('\', '/')
    $Root = ([System.IO.Path]::GetFullPath($Root)).TrimEnd('\', '/')
    $branch = (git -C $gitRoot symbolic-ref --quiet --short HEAD 2>$null).Trim()
    if ([string]::IsNullOrWhiteSpace($branch)) {
        $branch = "unborn-or-detached"
    }
    if ($repoRoot -eq $gitRoot) {
        $gitScope = "."
    } elseif ($repoRoot.StartsWith("$gitRoot\", [System.StringComparison]::OrdinalIgnoreCase)) {
        $gitScope = $repoRoot.Substring($gitRoot.Length + 1)
    } else {
        $gitScope = "."
    }
} catch {
}

function ConvertTo-HotStateSafeName {
    param([string]$Value)

    $safe = $Value -replace "/", "__"
    $safe = $safe -replace "[^A-Za-z0-9._-]+", "-"
    $safe = $safe -replace "-+", "-"
    return $safe.Trim("-")
}

$branchHotStatePath = ""
if ($branch -and $branch -notin @("unknown", "unborn-or-detached")) {
    $branchHotStatePath = Join-Path $hotStateBranchDir ("{0}.md" -f (ConvertTo-HotStateSafeName $branch))
}

$taskHotStatePath = ""
if ($CurrentTask) {
    $taskHotStatePath = Join-Path $hotStateTaskDir ([System.IO.Path]::GetFileName($CurrentTask))
}

$gitStatus = @()
try {
    if ($gitRoot) {
        $gitStatus = @(git -C $gitRoot status --short -- $gitScope 2>$null)
    } else {
        $gitStatus = @(git -C $repoRoot status --short 2>$null)
    }
} catch {
}

Write-Output "## Session Handoff"
Write-Output ""
Write-Output "- [x] timestamp: $timestamp"
Write-Output "- [x] branch: $branch"
Write-Output "- [x] git scope: $gitScope"
Write-Output "- [ ] active task: $CurrentTask"
Write-Output "- [ ] branch hot state file: $branchHotStatePath"
Write-Output "- [ ] task hot state file: $taskHotStatePath"
Write-Output "- [ ] files touched:"
if ($FilesTouched.Count -gt 0) {
    foreach ($item in $FilesTouched) {
        Write-Output "  - [ ] $item"
    }
} else {
    Write-Output "  - [ ] "
}

Write-Output "- [ ] commands run:"
if ($CommandsRun.Count -gt 0) {
    foreach ($item in $CommandsRun) {
        Write-Output "  - [ ] $item"
    }
} else {
    Write-Output "  - [ ] "
}

Write-Output "- [ ] open risk or blocker: $Risk"
Write-Output "- [ ] commit status: $CommitStatus"
Write-Output "- [ ] recommended commit message: $CommitMessage"
Write-Output "- [ ] recommended next step: $NextAction"
Write-Output "- [ ] backlog item: "
Write-Output "- [ ] waiting on user decision: "
Write-Output "- [ ] no next step because: "
Write-Output ""
Write-Output "## Context Checkpoint"
Write-Output ""
Write-Output "- [ ] true goal: "
Write-Output "- [ ] completed work: "
Write-Output "- [ ] remaining work: "
Write-Output "- [ ] next concrete action: $NextAction"
Write-Output "- [ ] risk / blocker: $Risk"
Write-Output "- [ ] latest validation status: "
Write-Output "- [ ] context action: continue / compact / new session"
Write-Output ""
Write-Output "- [x] git status snapshot:"
if ($gitStatus.Count -gt 0) {
    foreach ($line in $gitStatus) {
        Write-Output "  - [x] $line"
    }
} else {
    Write-Output "  - [x] clean or unavailable"
}
