#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: handoff-template.sh [--root /path/to/SDD] [--task TASK] [--file PATH] [--command CMD] [--risk TEXT] [--next TEXT]
       [--commit-status TEXT] [--commit-message TEXT] [--uncommitted-reason TEXT]
EOF
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$root/.." && pwd)"
current_task=""
risk=""
next_action=""
commit_status=""
commit_message=""
uncommitted_reason=""
hot_state_branch_dir="state/hot/branches"
hot_state_task_dir="state/hot/tasks"
declare -a files_touched=()
declare -a commands_run=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      root="$2"
      shift 2
      ;;
    --task)
      current_task="$2"
      shift 2
      ;;
    --file)
      files_touched+=("$2")
      shift 2
      ;;
    --command)
      commands_run+=("$2")
      shift 2
      ;;
    --risk)
      risk="$2"
      shift 2
      ;;
    --next)
      next_action="$2"
      shift 2
      ;;
    --commit-status)
      commit_status="$2"
      shift 2
      ;;
    --commit-message)
      commit_message="$2"
      shift 2
      ;;
    --uncommitted-reason)
      uncommitted_reason="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

if [[ -f "$root/workflow-config.env" ]]; then
  while IFS='=' read -r key value; do
    value="${value%$'\r'}"
    case "$key" in
      HOT_STATE_BRANCH_DIR)
        hot_state_branch_dir="$value"
        ;;
      HOT_STATE_TASK_DIR)
        hot_state_task_dir="$value"
        ;;
    esac
  done < "$root/workflow-config.env"
fi

sanitize_hot_state_name() {
  printf '%s' "$1" | sed -E 's#/#__#g; s#[^A-Za-z0-9._-]+#-#g; s#-+#-#g; s#^-+##; s#-+$##'
}

timestamp="$(date '+%Y-%m-%d %H:%M:%S %z')"
git_root="$(git -C "$repo_root" rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -n "$git_root" ]]; then
  branch="$(git -C "$git_root" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'unborn-or-detached')"
  if [[ "$repo_root" == "$git_root" ]]; then
    git_scope="."
  elif [[ "$repo_root" == "$git_root/"* ]]; then
    git_scope="${repo_root#"$git_root"/}"
  else
    git_scope="."
  fi
  git_status="$(git -C "$git_root" status --short -- "$git_scope" 2>/dev/null || true)"
else
  branch="unknown"
  git_scope="."
  git_status=""
fi

branch_hot_state_path=""
if [[ -n "$branch" && "$branch" != "unknown" && "$branch" != "unborn-or-detached" ]]; then
  branch_hot_state_path="$hot_state_branch_dir/$(sanitize_hot_state_name "$branch").md"
fi

task_hot_state_path=""
if [[ -n "$current_task" ]]; then
  task_hot_state_path="$hot_state_task_dir/$(basename "$current_task")"
fi

printf '## Session Handoff\n\n'
printf -- '- [x] timestamp: %s\n' "$timestamp"
printf -- '- [x] branch: %s\n' "$branch"
printf -- '- [x] git scope: %s\n' "$git_scope"
printf -- '- [ ] active task: %s\n' "$current_task"
printf -- '- [ ] branch hot state file: %s\n' "$branch_hot_state_path"
printf -- '- [ ] task hot state file: %s\n' "$task_hot_state_path"

printf -- '- [ ] files touched:\n'
if (( ${#files_touched[@]} > 0 )); then
  for item in "${files_touched[@]}"; do
    printf -- '  - [ ] %s\n' "$item"
  done
else
  printf -- '  - [ ] \n'
fi

printf -- '- [ ] commands run:\n'
if (( ${#commands_run[@]} > 0 )); then
  for item in "${commands_run[@]}"; do
    printf -- '  - [ ] %s\n' "$item"
  done
else
  printf -- '  - [ ] \n'
fi

printf -- '- [ ] open risk or blocker: %s\n' "$risk"
printf -- '- [ ] commit status: %s\n' "$commit_status"
printf -- '- [ ] uncommitted reason: %s\n' "$uncommitted_reason"
printf -- '- [ ] recommended commit message: %s\n' "$commit_message"
printf -- '- [ ] recommended next step: %s\n' "$next_action"
printf -- '- [ ] backlog item: \n'
printf -- '- [ ] waiting on user decision: \n'
printf -- '- [ ] no next step because: \n'
printf -- '- [x] git status snapshot:\n'
if [[ -n "$git_status" ]]; then
  while IFS= read -r line; do
    printf -- '  - [x] %s\n' "$line"
  done <<< "$git_status"
else
  printf -- '  - [x] clean or unavailable\n'
fi
