#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
config_path="$root/workflow-config.env"
external_issue_source="none"
connector_mode="pull-only"

if [[ -f "$config_path" ]]; then
  while IFS='=' read -r key value; do
    value="${value%$'\r'}"
    case "$key" in
      EXTERNAL_ISSUE_SOURCE)
        external_issue_source="$value"
        ;;
      CONNECTOR_MODE)
        connector_mode="$value"
        ;;
    esac
  done < "$config_path"
fi

echo "sync-external-items is a connector hook, not a full synchronizer."
echo "external issue source: $external_issue_source"
echo "connector mode: $connector_mode"
echo "Current behavior: document the external source boundary, then pull external planning context into repo-local backlog, sprint, or release artifacts manually."
echo "Future implementations may add provider-specific pull adapters for GitHub, Jira, or Linear."
