# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [string]$Root = ""
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$configPath = Join-Path $Root "workflow-config.env"
$externalIssueSource = "none"
$connectorMode = "pull-only"
if (Test-Path -LiteralPath $configPath) {
    foreach ($line in Get-Content -LiteralPath $configPath) {
        if ($line -match "^\s*EXTERNAL_ISSUE_SOURCE=(.+?)\s*$") {
            $externalIssueSource = $matches[1].Trim()
        }
        if ($line -match "^\s*CONNECTOR_MODE=(.+?)\s*$") {
            $connectorMode = $matches[1].Trim()
        }
    }
}

Write-Output "sync-external-items is a connector hook, not a full synchronizer."
Write-Output "external issue source: $externalIssueSource"
Write-Output "connector mode: $connectorMode"
Write-Output "Current behavior: document the external source boundary, then pull external planning context into repo-local backlog, sprint, or release artifacts manually."
Write-Output "Future implementations may add provider-specific pull adapters for GitHub, Jira, or Linear."
