#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
config_path="$root/workflow-config.env"
external_issue_source="none"
connector_mode="pull-only"

if [[ -f "$config_path" ]]; then
  while IFS='=' read -r key value; do
    value="${value%$'\r'}"
    case "$key" in
      EXTERNAL_ISSUE_SOURCE)
        external_issue_source="$value"
        ;;
      CONNECTOR_MODE)
        connector_mode="$value"
        ;;
    esac
  done < "$config_path"
fi

echo "sync-external-items 当前只是 connector hook，不是完整同步器。"
echo "external issue source: $external_issue_source"
echo "connector mode: $connector_mode"
echo "当前建议做法：先明确外部系统边界，再把外部规划上下文 pull 到 repo-local 的 backlog、sprint 或 release artifact 中。"
echo "后续版本可以为 GitHub、Jira、Linear 增加 provider-specific pull adapter。"
