# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [string]$Root = ""
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$configPath = Join-Path $Root "workflow-config.env"
$externalIssueSource = "none"
$connectorMode = "pull-only"
if (Test-Path -LiteralPath $configPath) {
    foreach ($line in Get-Content -LiteralPath $configPath) {
        if ($line -match "^\s*EXTERNAL_ISSUE_SOURCE=(.+?)\s*$") {
            $externalIssueSource = $matches[1].Trim()
        }
        if ($line -match "^\s*CONNECTOR_MODE=(.+?)\s*$") {
            $connectorMode = $matches[1].Trim()
        }
    }
}

Write-Output "sync-external-items 当前只是 connector hook，不是完整同步器。"
Write-Output "external issue source: $externalIssueSource"
Write-Output "connector mode: $connectorMode"
Write-Output "当前建议做法：先明确外部系统边界，再把外部规划上下文 pull 到 repo-local 的 backlog、sprint 或 release artifact 中。"
Write-Output "后续版本可以为 GitHub、Jira、Linear 增加 provider-specific pull adapter。"
