from __future__ import annotations

from pathlib import Path

from bootstrap_sdd_settings import BootstrapSettings


TEMPLATE_ROOT = Path(__file__).resolve().parent / "bootstrap_sdd_templates"

ROOT_README_TEMPLATES = {
    "zh-cn": TEMPLATE_ROOT / "root_readme.zh-cn.md.tmpl",
    "en": TEMPLATE_ROOT / "root_readme.en.md.tmpl",
}
ROOT_AGENTS_TEMPLATES = {
    "zh-cn": TEMPLATE_ROOT / "root_agents.zh-cn.md.tmpl",
    "en": TEMPLATE_ROOT / "root_agents.en.md.tmpl",
}
TESTING_GUIDE_TEMPLATES = {
    "zh-cn": TEMPLATE_ROOT / "testing_guide.zh-cn.md.tmpl",
    "en": TEMPLATE_ROOT / "testing_guide.en.md.tmpl",
}


def render_template(path: Path, **values: str) -> str:
    return path.read_text(encoding="utf-8").format(**values)


def workflow_config_content(sdd_dir: str, lang: str, workflow_profile: str, root_shims_enabled: bool) -> str:
    root_shims = "enabled" if root_shims_enabled else "disabled"
    return f"""# Generated by codex-sdd-workflow
SDD_DIR={sdd_dir}
LANG={lang}
WORKFLOW_PROFILE={workflow_profile}
ROOT_SHIMS={root_shims}
TASK_COMPLETION_GIT_MODE=manual
"""


def root_readme(repo_name: str, sdd_dir: str, lang: str) -> str:
    return render_template(ROOT_README_TEMPLATES[lang], repo_name=repo_name, sdd_dir=sdd_dir)


def root_agents(sdd_dir: str, lang: str) -> str:
    return render_template(ROOT_AGENTS_TEMPLATES[lang], sdd_dir=sdd_dir)


def testing_guide(settings: BootstrapSettings, stack: str, lang: str, sdd_dir: str) -> str:
    workflow_scripts = f"./{sdd_dir}/scripts"
    stack_defaults = "\n".join(settings.testing_guide_defaults[lang][stack])
    return render_template(
        TESTING_GUIDE_TEMPLATES[lang],
        workflow_scripts=workflow_scripts,
        stack_defaults=stack_defaults,
    )


def _next_step_context(target_root: Path, workflow_root: Path) -> dict[str, str]:
    return {
        "root_agents_path": str(target_root / "AGENTS.md"),
        "workflow_md_path": str(workflow_root / "workflow.md"),
        "process_md_path": str(workflow_root / "docs" / "process.md"),
        "session_brief_ps1": str(workflow_root / "scripts" / "session-brief.ps1"),
        "validate_ps1": str(workflow_root / "scripts" / "validate-sdd.ps1"),
        "new_task_ps1": str(workflow_root / "scripts" / "new-task.ps1"),
        "new_subtask_ps1": str(workflow_root / "scripts" / "new-subtask.ps1"),
        "archive_task_ps1": str(workflow_root / "scripts" / "archive-task.ps1"),
        "new_adr_ps1": str(workflow_root / "scripts" / "new-adr.ps1"),
        "handoff_ps1": str(workflow_root / "scripts" / "handoff-template.ps1"),
        "agile_delivery_md": str(workflow_root / "docs" / "agile-delivery.md"),
        "ci_cd_md": str(workflow_root / "docs" / "ci-cd.md"),
        "new_backlog_item_ps1": str(workflow_root / "scripts" / "new-backlog-item.ps1"),
        "new_sprint_ps1": str(workflow_root / "scripts" / "new-sprint.ps1"),
        "releases_dir": str(workflow_root / "releases"),
        "automation_dir": str(workflow_root / "automation"),
    }


def print_next_steps(
    settings: BootstrapSettings,
    target_root: Path,
    sdd_dir: str,
    stack: str,
    lang: str,
    workflow_profile: str,
    root_shims_enabled: bool,
) -> None:
    workflow_root = target_root / sdd_dir
    message_spec = settings.next_steps_messages[lang]
    context = _next_step_context(target_root, workflow_root)

    print(f"\n{message_spec['header']}")
    first_step_key = "root_step_enabled" if root_shims_enabled else "root_step_disabled"
    steps = [message_spec[first_step_key].format(**context)]
    steps.extend(step.format(**context) for step in message_spec["common_steps"])
    if workflow_profile == "full":
        steps.extend(step.format(**context) for step in message_spec["full_profile_steps"])

    for index, step in enumerate(steps, start=1):
        print(f"{index}. {step}")
    print(
        "\n"
        + message_spec["footer"].format(
            stack=stack,
            lang=lang,
            workflow_profile=workflow_profile,
        )
    )
