#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

usage() {
  echo "用法: $0 \"tasks/active/TASK-001-sample.md\" [--root /path/to/SDD] [--dry-run]"
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
dry_run=0
task_path=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      root="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ -z "$task_path" ]]; then
        task_path="$1"
        shift
      else
        usage
        exit 1
      fi
      ;;
  esac
done

if [[ -z "$task_path" ]]; then
  usage
  exit 1
fi

active_dir="$root/tasks/active"
history_dir="$root/tasks/history"

if [[ "$task_path" = /* ]]; then
  source_path="$(cd "$(dirname "$task_path")" && pwd)/$(basename "$task_path")"
else
  source_path="$(cd "$(dirname "$root/$task_path")" && pwd)/$(basename "$task_path")"
fi

case "$source_path" in
  "$active_dir"/*) ;;
  *)
    echo "只能归档 tasks/active/ 下的任务: $source_path" >&2
    exit 1
    ;;
esac

destination_path="$history_dir/$(basename "$source_path")"

if [[ "$dry_run" -eq 1 ]]; then
  echo "[DRY RUN] 将归档 $source_path -> $destination_path"
  exit 0
fi

mv "$source_path" "$destination_path"
echo "已归档 $destination_path"
echo "请同步更新 docs/process.md 与 docs/progress.md"
echo "进入下一次会话前，请留下下一步入口：新的 active task、progress.md 的推荐下一步，或 full profile 下的 backlog 条目。"
