# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$TaskPath,

    [string]$Root = "",

    [switch]$DryRun
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$activeDir = Join-Path $Root "tasks\active"
$historyDir = Join-Path $Root "tasks\history"

if ([System.IO.Path]::IsPathRooted($TaskPath)) {
    $sourcePath = (Resolve-Path $TaskPath).Path
} else {
    $sourcePath = (Resolve-Path (Join-Path $Root $TaskPath)).Path
}

if (-not $sourcePath.StartsWith($activeDir, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "只能归档 tasks/active/ 下的任务: $sourcePath"
}

$destinationPath = Join-Path $historyDir ([System.IO.Path]::GetFileName($sourcePath))

if ($DryRun) {
    Write-Host "[DRY RUN] 将归档 $sourcePath -> $destinationPath"
    exit 0
}

Move-Item -LiteralPath $sourcePath -Destination $destinationPath -Force
Write-Host "已归档 $destinationPath"
Write-Host "请同步更新 docs/process.md 与 docs/progress.md"
Write-Host "进入下一次会话前，请留下下一步入口：新的 active task、progress.md 的下一步选项推荐，或 full profile 下的 backlog 条目。"
