#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

usage() {
  cat <<'EOF'
用法: handoff-template.sh [--root /path/to/SDD] [--task TASK] [--file PATH] [--command CMD] [--risk TEXT] [--next TEXT]
       [--commit-status TEXT] [--commit-message TEXT] [--uncommitted-reason TEXT]
EOF
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$root/.." && pwd)"
current_task=""
risk=""
next_action=""
commit_status=""
commit_message=""
uncommitted_reason=""
declare -a files_touched=()
declare -a commands_run=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      root="$2"
      shift 2
      ;;
    --task)
      current_task="$2"
      shift 2
      ;;
    --file)
      files_touched+=("$2")
      shift 2
      ;;
    --command)
      commands_run+=("$2")
      shift 2
      ;;
    --risk)
      risk="$2"
      shift 2
      ;;
    --next)
      next_action="$2"
      shift 2
      ;;
    --commit-status)
      commit_status="$2"
      shift 2
      ;;
    --commit-message)
      commit_message="$2"
      shift 2
      ;;
    --uncommitted-reason)
      uncommitted_reason="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

timestamp="$(date '+%Y-%m-%d %H:%M:%S %z')"
git_root="$(git -C "$repo_root" rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -n "$git_root" ]]; then
  branch="$(git -C "$git_root" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'unborn-or-detached')"
  if [[ "$repo_root" == "$git_root" ]]; then
    git_scope="."
  elif [[ "$repo_root" == "$git_root/"* ]]; then
    git_scope="${repo_root#"$git_root"/}"
  else
    git_scope="."
  fi
  git_status="$(git -C "$git_root" status --short -- "$git_scope" 2>/dev/null || true)"
else
  branch="unknown"
  git_scope="."
  git_status=""
fi

printf '## Session Handoff\n\n'
printf -- '- [x] 时间戳: %s\n' "$timestamp"
printf -- '- [x] 分支: %s\n' "$branch"
printf -- '- [x] git 范围: %s\n' "$git_scope"
printf -- '- [ ] active task: %s\n' "$current_task"

printf -- '- [ ] 涉及文件:\n'
if (( ${#files_touched[@]} > 0 )); then
  for item in "${files_touched[@]}"; do
    printf -- '  - [ ] %s\n' "$item"
  done
else
  printf -- '  - [ ] \n'
fi

printf -- '- [ ] 执行命令:\n'
if (( ${#commands_run[@]} > 0 )); then
  for item in "${commands_run[@]}"; do
    printf -- '  - [ ] %s\n' "$item"
  done
else
  printf -- '  - [ ] \n'
fi

printf -- '- [ ] 未解决风险或 blocker：%s\n' "$risk"
printf -- '- [ ] commit status: %s\n' "$commit_status"
printf -- '- [ ] 未提交原因: %s\n' "$uncommitted_reason"
printf -- '- [ ] 推荐 commit message: %s\n' "$commit_message"
printf -- '- [ ] 推荐的下一步明确动作：%s\n' "$next_action"
printf -- '- [ ] 等待用户决策：\n'
printf -- '- [ ] 无需下一步原因：\n'
printf -- '- [x] git 状态快照:\n'
if [[ -n "$git_status" ]]; then
  while IFS= read -r line; do
    printf -- '  - [x] %s\n' "$line"
  done <<< "$git_status"
else
  printf -- '  - [x] 工作区干净或 git 不可用\n'
fi
