#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

usage() {
  echo "用法: $0 \"tasks/TASK-001-parent-task.md\" \"subtask 标题\" [--root /path/to/SDD] [--dry-run]"
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
dry_run=0
parent_task=""
title=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      root="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ -z "$parent_task" ]]; then
        parent_task="$1"
        shift
      elif [[ -z "$title" ]]; then
        title="$1"
        shift
      else
        usage
        exit 1
      fi
      ;;
  esac
done

if [[ -z "$parent_task" || -z "$title" ]]; then
  usage
  exit 1
fi

tasks_dir="$root/tasks"
active_dir="$tasks_dir/active"
template_path="$root/templates/tasks/SUBTASK-template.md"
lock_dir="$active_dir/.new-subtask.lock"

if [[ ! -f "$template_path" ]]; then
  echo "未找到 subtask 模板: $template_path" >&2
  exit 1
fi

slug="$(printf '%s' "$title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
if [[ -z "$slug" ]]; then
  slug="subtask"
fi

parent_id="000"
if [[ "$parent_task" =~ TASK-([0-9]{3}) ]]; then
  parent_id="${BASH_REMATCH[1]}"
fi

while ! mkdir "$lock_dir" 2>/dev/null; do
  sleep 0.1
done
trap 'rmdir "$lock_dir" 2>/dev/null || true' EXIT

max_id=0
shopt -s nullglob
for path in "$active_dir"/SUBTASK-${parent_id}-*.md; do
  name="$(basename "$path")"
  if [[ "$name" =~ ^SUBTASK-[0-9]{3}-([0-9]{2})(-.*)?\.md$ ]]; then
    current_id=$((10#${BASH_REMATCH[1]}))
    if (( current_id > max_id )); then
      max_id=$current_id
    fi
  fi
done

next_id=$((max_id + 1))
sub_id="$(printf '%02d' "$next_id")"
full_id="${parent_id}-${sub_id}"
target_path="$active_dir/SUBTASK-$full_id-$slug.md"

legacy_parent_label="父""任务"
rendered="$(awk -v id="$full_id" -v title="$title" -v parent="$parent_task" -v legacy_parent_label="$legacy_parent_label" '
NR == 1 { print "# SUBTASK-" id ": " title; next }
$0 == "- draft / ready / in_progress / blocked / done" || $0 == "- [ ] draft / ready / in_progress / blocked / done" { print "- [ ] ready"; next }
$0 == "- parent task: `tasks/TASK-XXX-parent-task.md`" || $0 == "- parent task: `tasks/active/TASK-XXX-parent-task.md`" || $0 == "- [ ] parent task: `tasks/TASK-XXX-parent-task.md`" || $0 == "- [ ] parent task: `tasks/active/TASK-XXX-parent-task.md`" { print "- [ ] parent task: `" parent "`"; next }
$0 == "- " legacy_parent_label "：`tasks/TASK-XXX-parent-task.md`" || $0 == "- " legacy_parent_label "：`tasks/active/TASK-XXX-parent-task.md`" || $0 == "- [ ] " legacy_parent_label "：`tasks/TASK-XXX-parent-task.md`" || $0 == "- [ ] " legacy_parent_label "：`tasks/active/TASK-XXX-parent-task.md`" { print "- [ ] parent task: `" parent "`"; next }
{ print }
' "$template_path")"

if [[ "$dry_run" -eq 1 ]]; then
  echo "[DRY RUN] 将创建 $target_path"
  printf '%s\n' "$rendered"
  exit 0
fi

printf '%s\n' "$rendered" > "$target_path"
echo "已创建 $target_path"
