#!/usr/bin/env bash
# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$root/.." && pwd)"
progress_path="$root/docs/progress.md"
process_path="$root/docs/process.md"
active_tasks_dir="$root/tasks/active"
history_tasks_dir="$root/tasks/history"
git_root="$(git -C "$repo_root" rev-parse --show-toplevel 2>/dev/null || true)"
workflow_profile="lite"
task_completion_git_mode="manual"
if [[ -f "$root/workflow-config.env" ]]; then
  while IFS='=' read -r key value; do
    value="${value%$'\r'}"
    case "$key" in
      WORKFLOW_PROFILE)
        workflow_profile="$value"
        ;;
      TASK_COMPLETION_GIT_MODE)
        task_completion_git_mode="$value"
        ;;
    esac
  done < "$root/workflow-config.env"
fi

section() {
  local heading="$1"
  awk -v target="## $heading" '
  $0 == target { capture=1; next }
  capture && /^## / { exit }
  capture { print }
  ' "$2"
}

timestamp="$(date '+%Y-%m-%d %H:%M:%S %z')"
if [[ -n "$git_root" ]]; then
  branch="$(git -C "$git_root" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'unborn-or-detached')"
  if [[ "$repo_root" == "$git_root" ]]; then
    git_scope="."
  elif [[ "$repo_root" == "$git_root/"* ]]; then
    git_scope="${repo_root#"$git_root"/}"
  else
    git_scope="."
  fi
  git_status="$(git -C "$git_root" status --short -- "$git_scope" 2>/dev/null || true)"
else
  branch="unknown"
  git_scope="."
  git_status=""
fi

printf '# 会话摘要\n\n'
printf -- '- 仓库根目录: %s\n' "$repo_root"
printf -- '- workflow 根目录: %s\n' "$root"
printf -- '- workflow profile: %s\n' "$workflow_profile"
printf -- '- task completion git mode: %s\n' "$task_completion_git_mode"
printf -- '- 时间戳: %s\n' "$timestamp"
printf -- '- 当前分支: %s\n' "$branch"
printf -- '- git 范围: %s\n\n' "$git_scope"

for heading in "当前焦点" "当前任务板" "近期完成" "归档规则"; do
  if [[ -f "$process_path" ]]; then
    body="$(section "$heading" "$process_path")"
    if [[ -n "$body" ]]; then
      printf '## %s\n%s\n\n' "$heading" "$body"
    fi
  fi
done

legacy_git_handoff_heading="Git 收""口"
legacy_blockers_heading="阻塞""项"
for heading in "当前摘要" "当前" "Git handoff" "$legacy_git_handoff_heading" "下一步选项" "下一步" "并行工作摘要" "Blockers" "$legacy_blockers_heading"; do
  if [[ -f "$progress_path" ]]; then
    body="$(section "$heading" "$progress_path")"
    if [[ -n "$body" ]]; then
      printf '## %s\n%s\n\n' "$heading" "$body"
    fi
  fi
done

printf '## Git 状态\n'
if [[ -n "$git_status" ]]; then
  while IFS= read -r line; do
    printf -- '- %s\n' "$line"
  done <<< "$git_status"
else
  printf -- '- 工作区干净或 git 不可用\n'
fi
printf '\n'

printf '## 最近的 Task Cards\n'
recent=0
shopt -s nullglob
task_paths=("$active_tasks_dir"/TASK-*.md)
if (( ${#task_paths[@]} > 0 )); then
  mapfile -t task_paths < <(ls -1t "${task_paths[@]}")
  for path in "${task_paths[@]}"; do
    name="$(basename "$path")"
    printf -- '- %s\n' "$name"
    recent=$((recent + 1))
    if (( recent == 5 )); then
      break
    fi
  done
fi

if (( recent == 0 )); then
  printf -- '- 还没有真实 task\n'
fi

printf '\n## 最近的 Subtasks\n'
recent=0
subtask_paths=("$active_tasks_dir"/SUBTASK-*.md)
if (( ${#subtask_paths[@]} > 0 )); then
  mapfile -t subtask_paths < <(ls -1t "${subtask_paths[@]}")
  for path in "${subtask_paths[@]}"; do
    name="$(basename "$path")"
    printf -- '- %s\n' "$name"
    recent=$((recent + 1))
    if (( recent == 5 )); then
      break
    fi
  done
fi

if (( recent == 0 )); then
  printf -- '- 还没有真实 subtask\n'
fi

printf '\n## 最近归档的任务\n'
recent=0
history_paths=("$history_tasks_dir"/*.md)
if (( ${#history_paths[@]} > 0 )); then
  mapfile -t history_paths < <(ls -1t "${history_paths[@]}")
  for path in "${history_paths[@]}"; do
    printf -- '- %s\n' "$(basename "$path")"
    recent=$((recent + 1))
    if (( recent == 5 )); then
      break
    fi
  done
fi

if (( recent == 0 )); then
  printf -- '- 还没有归档任务\n'
fi
