# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [string]$Root = ""
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$repoRoot = (Resolve-Path (Join-Path $Root "..")).Path
$processPath = Join-Path $Root "docs\process.md"
$progressPath = Join-Path $Root "docs\progress.md"
$activeTasksDir = Join-Path $Root "tasks\active"
$historyTasksDir = Join-Path $Root "tasks\history"
$workflowProfile = "lite"
$taskCompletionGitMode = "manual"
$hotStateMode = "branch-aware"
$hotStateBranchDir = "state/hot/branches"
$hotStateTaskDir = "state/hot/tasks"
$externalIssueSource = "none"
$connectorMode = "pull-only"
try {
    foreach ($line in Get-Content -LiteralPath (Join-Path $Root "workflow-config.env") -ErrorAction Stop) {
        if ($line -match "^\s*WORKFLOW_PROFILE=(.+?)\s*$") {
            $workflowProfile = $matches[1].Trim()
        }
        if ($line -match "^\s*TASK_COMPLETION_GIT_MODE=(.+?)\s*$") {
            $taskCompletionGitMode = $matches[1].Trim()
        }
        if ($line -match "^\s*HOT_STATE_MODE=(.+?)\s*$") {
            $hotStateMode = $matches[1].Trim()
        }
        if ($line -match "^\s*HOT_STATE_BRANCH_DIR=(.+?)\s*$") {
            $hotStateBranchDir = $matches[1].Trim()
        }
        if ($line -match "^\s*HOT_STATE_TASK_DIR=(.+?)\s*$") {
            $hotStateTaskDir = $matches[1].Trim()
        }
        if ($line -match "^\s*EXTERNAL_ISSUE_SOURCE=(.+?)\s*$") {
            $externalIssueSource = $matches[1].Trim()
        }
        if ($line -match "^\s*CONNECTOR_MODE=(.+?)\s*$") {
            $connectorMode = $matches[1].Trim()
        }
    }
} catch {
}

function Get-MarkdownSection {
    param(
        [string]$Path,
        [string]$Heading
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return ""
    }

    $target = "## $Heading"
    $capture = $false
    $lines = New-Object System.Collections.Generic.List[string]

    foreach ($line in Get-Content -LiteralPath $Path) {
        if ($line -eq $target) {
            $capture = $true
            continue
        }

        if ($capture -and $line -match "^## ") {
            break
        }

        if ($capture) {
            $lines.Add($line)
        }
    }

    return ($lines -join [Environment]::NewLine).Trim()
}

function ConvertTo-HotStateSafeName {
    param([string]$Value)

    $safe = $Value -replace "/", "__"
    $safe = $safe -replace "[^A-Za-z0-9._-]+", "-"
    $safe = $safe -replace "-+", "-"
    return $safe.Trim("-")
}

function Get-CurrentTaskReference {
    if (-not (Test-Path -LiteralPath $progressPath)) {
        return ""
    }
    $currentBody = Get-MarkdownSection -Path $progressPath -Heading "Current"
    foreach ($line in ($currentBody -split "`r?`n")) {
        if ($line -match "^\s*-\s*\[[ xX]\]\s*(active task|当前 Active Task)[:：]\s*(.+?)\s*$") {
            return $matches[2].Trim().Trim([char]96)
        }
    }
    return ""
}

function Write-MarkdownFileSection {
    param(
        [string]$Heading,
        [string]$Path,
        [string]$EmptyMessage
    )

    Write-Output "## $Heading"
    if (Test-Path -LiteralPath $Path) {
        Get-Content -LiteralPath $Path | Write-Output
    } else {
        Write-Output "- $EmptyMessage"
    }
    Write-Output ""
}

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
$branch = "unknown"
$gitRoot = ""
$gitScope = "."
try {
    $gitRoot = (git -C $repoRoot rev-parse --show-toplevel 2>$null).Trim()
    $gitRoot = ([System.IO.Path]::GetFullPath($gitRoot)).TrimEnd('\', '/')
    $repoRoot = ([System.IO.Path]::GetFullPath($repoRoot)).TrimEnd('\', '/')
    if (-not [string]::IsNullOrWhiteSpace($gitRoot)) {
        $branch = (git -C $gitRoot symbolic-ref --quiet --short HEAD 2>$null).Trim()
        if ([string]::IsNullOrWhiteSpace($branch)) {
            $branch = "unborn-or-detached"
        }
        if ($repoRoot -eq $gitRoot) {
            $gitScope = "."
        } elseif ($repoRoot.StartsWith("$gitRoot\", [System.StringComparison]::OrdinalIgnoreCase)) {
            $gitScope = $repoRoot.Substring($gitRoot.Length + 1)
        } else {
            $gitScope = "."
        }
    }
} catch {
}

$gitStatus = @()
try {
    if ($gitRoot) {
        $gitStatus = @(git -C $gitRoot status --short -- $gitScope 2>$null)
    } else {
        $gitStatus = @(git -C $repoRoot status --short 2>$null)
    }
} catch {
}

$branchHotStatePath = ""
if ($branch -and $branch -notin @("unknown", "unborn-or-detached")) {
    $branchHotStatePath = Join-Path $Root $hotStateBranchDir
    $branchHotStatePath = Join-Path $branchHotStatePath ("{0}.md" -f (ConvertTo-HotStateSafeName $branch))
}

$taskHotStatePath = ""
$currentTaskRef = Get-CurrentTaskReference
if ($currentTaskRef -and $currentTaskRef -ne "none" -and $currentTaskRef -notmatch "TASK-XXX") {
    $taskHotStatePath = Join-Path $Root $hotStateTaskDir
    $taskHotStatePath = Join-Path $taskHotStatePath ([System.IO.Path]::GetFileName($currentTaskRef))
}

$legacyGitHandoffHeading = "Git " + "收" + "口"
$legacyBlockersHeading = "阻碍与风险"

Write-Output "# Session Brief"
Write-Output ""
Write-Output "- repo root: $repoRoot"
Write-Output "- workflow root: $Root"
Write-Output "- workflow profile: $workflowProfile"
Write-Output "- task completion git mode: $taskCompletionGitMode"
Write-Output "- hot state mode: $hotStateMode"
Write-Output "- external issue source: $externalIssueSource"
Write-Output "- connector mode: $connectorMode"
Write-Output "- timestamp: $timestamp"
Write-Output "- branch: $branch"
Write-Output "- git scope: $gitScope"
Write-Output ""

foreach ($heading in @("Macro Focus", "Rules of Archiving", "Recent History", "Pointers", "Current Focus", "近期归档", "Workflow Rules & Index", "当前焦点", "当前任务板", "近期完成", "归档规则")) {
    $body = Get-MarkdownSection -Path $processPath -Heading $heading
    if ($body) {
        Write-Output "## $heading"
        Write-Output $body
        Write-Output ""
    }
}

foreach ($heading in @("Current", "Recent Findings", "Session Handoff", "Concurrency", "当前上下文", "协作区", "当前摘要", "当前", "Git handoff", $legacyGitHandoffHeading, "下一步选项", "下一步", "并行工作摘要", "Blockers", $legacyBlockersHeading)) {
    $body = Get-MarkdownSection -Path $progressPath -Heading $heading
    if ($body) {
        Write-Output "## $heading"
        Write-Output $body
        Write-Output ""
    }
}

if ($branchHotStatePath) {
    Write-MarkdownFileSection -Heading "Active Branch Hot State" -Path $branchHotStatePath -EmptyMessage "当前 branch 还没有热状态便签"
}

if ($taskHotStatePath) {
    Write-MarkdownFileSection -Heading "Active Task Hot State" -Path $taskHotStatePath -EmptyMessage "当前 active task 还没有热状态便签"
}

Write-Output "## Git Status"
if ($gitStatus.Count -gt 0) {
    foreach ($line in $gitStatus) {
        Write-Output "- $line"
    }
} else {
    Write-Output "- clean or unavailable"
}
Write-Output ""

Write-Output "## Recent Task Cards"
$recentTasks = Get-ChildItem -Path $activeTasksDir -Filter "TASK-*.md" -File -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 5

if ($recentTasks) {
    foreach ($task in $recentTasks) {
        Write-Output "- $($task.Name)"
    }
} else {
    Write-Output "- no concrete task cards yet"
}
Write-Output ""

Write-Output "## Recent Subtasks"
$recentSubtasks = Get-ChildItem -Path $activeTasksDir -Filter "SUBTASK-*.md" -File -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 5

if ($recentSubtasks) {
    foreach ($subtask in $recentSubtasks) {
        Write-Output "- $($subtask.Name)"
    }
} else {
    Write-Output "- no concrete subtasks yet"
}
Write-Output ""

Write-Output "## Recently Archived"
$recentHistory = Get-ChildItem -Path $historyTasksDir -Filter "*.md" -File -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 5

if ($recentHistory) {
    foreach ($item in $recentHistory) {
        Write-Output "- $($item.Name)"
    }
} else {
    Write-Output "- no archived work yet"
}
