# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [string]$Root = ""
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$repoRoot = (Resolve-Path (Join-Path $Root "..")).Path
$processPath = Join-Path $Root "docs\process.md"
$progressPath = Join-Path $Root "docs\progress.md"
$activeTasksDir = Join-Path $Root "tasks\active"
$historyTasksDir = Join-Path $Root "tasks\history"
$workflowProfile = "lite"
$taskCompletionGitMode = "manual"
try {
    foreach ($line in Get-Content -LiteralPath (Join-Path $Root "workflow-config.env") -ErrorAction Stop) {
        if ($line -match "^\s*WORKFLOW_PROFILE=(.+?)\s*$") {
            $workflowProfile = $matches[1].Trim()
        }
        if ($line -match "^\s*TASK_COMPLETION_GIT_MODE=(.+?)\s*$") {
            $taskCompletionGitMode = $matches[1].Trim()
        }
    }
} catch {
}

function Get-MarkdownSection {
    param(
        [string]$Path,
        [string]$Heading
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return ""
    }

    $target = "## $Heading"
    $capture = $false
    $lines = New-Object System.Collections.Generic.List[string]

    foreach ($line in Get-Content -LiteralPath $Path) {
        if ($line -eq $target) {
            $capture = $true
            continue
        }

        if ($capture -and $line -match "^## ") {
            break
        }

        if ($capture) {
            $lines.Add($line)
        }
    }

    return ($lines -join [Environment]::NewLine).Trim()
}

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
$branch = "unknown"
$gitRoot = ""
$gitScope = "."
try {
    $gitRoot = (git -C $repoRoot rev-parse --show-toplevel 2>$null).Trim()
    $gitRoot = ([System.IO.Path]::GetFullPath($gitRoot)).TrimEnd('\', '/')
    $repoRoot = ([System.IO.Path]::GetFullPath($repoRoot)).TrimEnd('\', '/')
    $branch = (git -C $gitRoot symbolic-ref --quiet --short HEAD 2>$null).Trim()
    if ([string]::IsNullOrWhiteSpace($branch)) {
        $branch = "unborn-or-detached"
    }
    if ($repoRoot -eq $gitRoot) {
        $gitScope = "."
    } elseif ($repoRoot.StartsWith("$gitRoot\", [System.StringComparison]::OrdinalIgnoreCase)) {
        $gitScope = $repoRoot.Substring($gitRoot.Length + 1)
    } else {
        $gitScope = "."
    }
} catch {
}

$gitStatus = @()
try {
    if ($gitRoot) {
        $gitStatus = @(git -C $gitRoot status --short -- $gitScope 2>$null)
    } else {
        $gitStatus = @(git -C $repoRoot status --short 2>$null)
    }
} catch {
}

Write-Output "# 会话摘要"
Write-Output ""
Write-Output "- 仓库根目录: $repoRoot"
Write-Output "- workflow 根目录: $Root"
Write-Output "- workflow profile: $workflowProfile"
Write-Output "- task completion git mode: $taskCompletionGitMode"
Write-Output "- 时间戳: $timestamp"
Write-Output "- 当前分支: $branch"
Write-Output "- git 范围: $gitScope"
Write-Output ""

foreach ($heading in @("Macro Focus", "Rules of Archiving", "Recent History", "Pointers", "Current Focus", "近期归档", "Workflow Rules & Index", "当前焦点", "当前任务板", "近期完成", "归档规则")) {
    $body = Get-MarkdownSection -Path $processPath -Heading $heading
    if ($body) {
        Write-Output "## $heading"
        Write-Output $body
        Write-Output ""
    }
}

$legacyGitHandoffHeading = "Git " + "收" + "口"
$legacyBlockersHeading = "阻塞" + "项"
foreach ($heading in @("Current", "Recent Findings", "Session Handoff", "Concurrency", "当前上下文", "协作区", "当前摘要", "当前", "Git handoff", $legacyGitHandoffHeading, "下一步选项", "下一步", "并行工作摘要", "Blockers", $legacyBlockersHeading)) {
    $body = Get-MarkdownSection -Path $progressPath -Heading $heading
    if ($body) {
        Write-Output "## $heading"
        Write-Output $body
        Write-Output ""
    }
}

Write-Output "## Git 状态"
if ($gitStatus.Count -gt 0) {
    foreach ($line in $gitStatus) {
        Write-Output "- $line"
    }
} else {
    Write-Output "- 工作区干净或 git 不可用"
}
Write-Output ""

Write-Output "## 最近的 Task Cards"
$recentTasks = Get-ChildItem -Path $activeTasksDir -Filter "TASK-*.md" -File -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 5

if ($recentTasks) {
    foreach ($task in $recentTasks) {
        Write-Output "- $($task.Name)"
    }
} else {
    Write-Output "- 还没有真实 task"
}
Write-Output ""

Write-Output "## 最近的 Subtasks"
$recentSubtasks = Get-ChildItem -Path $activeTasksDir -Filter "SUBTASK-*.md" -File -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 5

if ($recentSubtasks) {
    foreach ($subtask in $recentSubtasks) {
        Write-Output "- $($subtask.Name)"
    }
} else {
    Write-Output "- 还没有真实 subtask"
}
Write-Output ""

Write-Output "## 最近归档的任务"
$recentHistory = Get-ChildItem -Path $historyTasksDir -Filter "*.md" -File -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 5

if ($recentHistory) {
    foreach ($item in $recentHistory) {
        Write-Output "- $($item.Name)"
    }
} else {
    Write-Output "- 还没有归档任务"
}
