# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [string]$Root = "",
    [switch]$Strict
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$configPath = Join-Path $Root "workflow-config.env"
$rootShimsEnabled = $true
$workflowProfile = "lite"
$lang = "en"
$taskCompletionGitMode = "manual"
$hotStateMode = "branch-aware"
$hotStateBranchDir = "state/hot/branches"
$hotStateTaskDir = "state/hot/tasks"
$hotStateHistoryDir = "state/history"
$externalIssueSource = "none"
$connectorMode = "pull-only"
$templateOverlay = "none"
if (Test-Path -LiteralPath $configPath) {
    foreach ($line in Get-Content -LiteralPath $configPath) {
        if ($line -match "^\s*ROOT_SHIMS=(.+?)\s*$") {
            $rootShimsEnabled = $matches[1].Trim() -ne "disabled"
        }
        if ($line -match "^\s*WORKFLOW_PROFILE=(.+?)\s*$") {
            $workflowProfile = $matches[1].Trim()
        }
        if ($line -match "^\s*LANG=(.+?)\s*$") {
            $lang = $matches[1].Trim()
        }
        if ($line -match "^\s*TASK_COMPLETION_GIT_MODE=(.+?)\s*$") {
            $taskCompletionGitMode = $matches[1].Trim()
        }
        if ($line -match "^\s*HOT_STATE_MODE=(.+?)\s*$") {
            $hotStateMode = $matches[1].Trim()
        }
        if ($line -match "^\s*HOT_STATE_BRANCH_DIR=(.+?)\s*$") {
            $hotStateBranchDir = $matches[1].Trim()
        }
        if ($line -match "^\s*HOT_STATE_TASK_DIR=(.+?)\s*$") {
            $hotStateTaskDir = $matches[1].Trim()
        }
        if ($line -match "^\s*HOT_STATE_HISTORY_DIR=(.+?)\s*$") {
            $hotStateHistoryDir = $matches[1].Trim()
        }
        if ($line -match "^\s*EXTERNAL_ISSUE_SOURCE=(.+?)\s*$") {
            $externalIssueSource = $matches[1].Trim()
        }
        if ($line -match "^\s*CONNECTOR_MODE=(.+?)\s*$") {
            $connectorMode = $matches[1].Trim()
        }
        if ($line -match "^\s*TEMPLATE_OVERLAY=(.+?)\s*$") {
            $templateOverlay = $matches[1].Trim()
        }
    }
}

$requiredPaths = @(
    "workflow-config.env",
    "README.md",
    "workflow.md",
    "docs\project-brief.md",
    "docs\process.md",
    "docs\architecture.md",
    "docs\testing.md",
    "docs\git-workflow.md",
    "docs\progress.md",
    "docs\workflow-audit.md",
    "tasks\active",
    "tasks\history",
    "templates\README.md",
    "templates\overlays\README.md",
    "templates\tasks\TASK-template.md",
    "templates\tasks\SUBTASK-template.md",
    "templates\adr\ADR-000-template.md",
    "templates\evidence\EVIDENCE-000-template.md",
    "adr\README.md",
    "adr\records",
    "scripts\new-task.ps1",
    "scripts\new-task.sh",
    "scripts\new-subtask.ps1",
    "scripts\new-subtask.sh",
    "scripts\new-adr.ps1",
    "scripts\new-adr.sh",
    "scripts\archive-task.ps1",
    "scripts\archive-task.sh",
    "scripts\session-brief.ps1",
    "scripts\session-brief.sh",
    "scripts\validate-sdd.ps1",
    "scripts\validate-sdd.sh",
    "scripts\handoff-template.ps1",
    "scripts\handoff-template.sh",
    "evidence\README.md",
    "state\README.md",
    ($hotStateBranchDir -replace "/", "\") + "\README.md",
    ($hotStateTaskDir -replace "/", "\") + "\README.md",
    ($hotStateHistoryDir -replace "/", "\") + "\README.md"
)

if ($rootShimsEnabled) {
    $requiredPaths = @("..\AGENTS.md", "..\README.md") + $requiredPaths
}

if ($workflowProfile -eq "full") {
    $requiredPaths += @(
        "docs\agile-delivery.md",
        "docs\ci-cd.md",
        "backlog\README.md",
        "backlog\items",
        "sprints\README.md",
        "sprints\active",
        "sprints\history",
        "releases\README.md",
        "releases\records",
        "automation\README.md",
        "automation\github-actions\ci.yml.example",
        "templates\backlog\BACKLOG-ITEM-template.md",
        "templates\sprints\SPRINT-template.md",
        "templates\releases\RELEASE-template.md",
        "scripts\new-backlog-item.ps1",
        "scripts\new-backlog-item.sh",
        "scripts\new-sprint.ps1",
        "scripts\new-sprint.sh",
        "scripts\new-release.ps1",
        "scripts\new-release.sh",
        "scripts\sync-external-items.ps1",
        "scripts\sync-external-items.sh"
    )
}

if ($templateOverlay -ne "none") {
    $requiredPaths += "templates\overlays\active\manifest.json"
}

$placeholderPatterns = @(
    "^\s*-\s*\[\s\]\s*current phase:\s*$",
    "^\s*-\s*\[\s\]\s*active task:\s*$",
    "^\s*-\s*\[\s\]\s*active task: `tasks/active/TASK-XXX.*\.md`\s*$",
    "^\s*-\s*\[\s\]\s*active branch hot state:\s*$",
    "^\s*-\s*\[\s\]\s*active task hot state:\s*$",
    "^\s*-\s*\[\s\]\s*latest verified summary:\s*$",
    "^\s*-\s*\[\s\]\s*\[YYYY-MM-DD\]\s*finding:\s*$",
    "^\s*-\s*\[\s\]\s*\[YYYY-MM-DD\]\s*conclusion:\s*$",
    "^\s*-\s*\[\s\]\s*branch-aware hot state checked:\s*$",
    "^\s*-\s*\[\s\]\s*integration status:\s*$",
    "^\s*Describe the product or system in one sentence\.\s*$",
    "^\s*-\s*What pain does this project solve\?\s*$"
)

$missing = New-Object System.Collections.Generic.List[string]
$warnings = New-Object System.Collections.Generic.List[string]
$contractFailures = New-Object System.Collections.Generic.List[string]

function Test-NextStepSignal {
    param([string]$RootPath)

    $progressPath = Join-Path $RootPath "docs\progress.md"
    if (-not (Test-Path -LiteralPath $progressPath)) {
        return $false
    }

    foreach ($line in Get-Content -LiteralPath $progressPath) {
        $normalized = $line -replace "^\s*-\s*(?:\[[ xX]\]\s*)?", ""
        if ($normalized -match "^(recommended next step|next active task|backlog item|waiting on user decision|no next step because|推荐下一步|推荐的下一步明确动作|下一步 active task|backlog 条目|等待用户决策|无需下一步原因)[:：]\s*(\S.*)$") {
            $value = $matches[2].Trim()
            if ($value -notmatch "^(none|n/a|N/A|无)$" -and $value -notmatch "(TASK-XXX|BACKLOG-XXX|sample)") {
                return $true
            }
        }
    }

    return $false
}

function Test-CompletedTaskFile {
    param([System.IO.FileInfo]$Path)

    $historyDir = [System.IO.Path]::GetFullPath((Join-Path $Root "tasks\history")).TrimEnd('\', '/')
    $taskPath = [System.IO.Path]::GetFullPath($Path.FullName)
    if ($taskPath.StartsWith("$historyDir\", [System.StringComparison]::OrdinalIgnoreCase)) {
        return $true
    }

    $raw = Get-Content -LiteralPath $Path.FullName -Raw
    return ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?(status|commit status|Git commit 状态)[:：]\s*(done|complete|committed|已完成|已提交)\s*$") -or
        ($raw -match "(?im)^-\s*\[[xX]\]\s*(done|complete|committed|已完成|已提交)\s*$") -or
        ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?(done|complete)\s*$")
}

function Test-ManualGitClosure {
    param([string]$Raw)

    return (($Raw -match "(?im)commit status[:：]\s*(not committed|未提交)") -or
        ($Raw -match "(?im)Git commit 状态[:：]\s*未提交")) -and
        ($Raw -match "(?im)(uncommitted reason|未提交原因)[:：]\s*\S") -and
        ($Raw -match "(?im)(recommended commit message|推荐 commit message)[:：]\s*\S")
}

function Test-AutoGitClosure {
    param([string]$Raw)

    return (($Raw -match "(?im)commit status[:：]\s*(committed|已提交)") -or
        ($Raw -match "(?im)Git commit 状态[:：]\s*已提交")) -and
        ($Raw -match "(?im)(commit hash|commit message|recommended commit message|推荐 commit message)[:：]\s*\S")
}

function Test-TemplateContract {
    param([string]$RelativePath)

    $absolutePath = Join-Path $Root $RelativePath
    $relativeKey = $RelativePath -replace "\\", "/"
    $markers = @()
    switch ("$lang`:$relativeKey") {
        "en:templates/tasks/TASK-template.md" {
            $markers = @("## Status", "## Completion Handoff", "- [ ] commit status:", "- [ ] recommended next step:")
        }
        "en:templates/tasks/SUBTASK-template.md" {
            $markers = @("## Parent Task", "## Completion Handoff", "- [ ] commit status:", "- [ ] recommended next step:")
        }
        "en:templates/evidence/EVIDENCE-000-template.md" {
            $markers = @("## Goal", "## Results And Findings", "- [ ] expected result:", "- [ ] validation result: pass / fail / partial")
        }
        "en:templates/releases/RELEASE-template.md" {
            $markers = @("## Checks", "## Next Options", "- [ ] CI checks:", "- [ ] recommended next step:")
        }
        "zh-cn:templates/tasks/TASK-template.md" {
            $markers = @("## 状态", "## Completion Handoff", "- [ ] Git commit 状态：未提交 / 已提交", "- [ ] 推荐的下一步排期 (Next Task)：")
        }
        "zh-cn:templates/tasks/SUBTASK-template.md" {
            $markers = @("## Parent Task", "## Completion Handoff", "- [ ] commit status：未提交 / 已提交", "- [ ] 推荐下一步：")
        }
        "zh-cn:templates/evidence/EVIDENCE-000-template.md" {
            $markers = @("## 目标", "## 结果与发现", "- [ ] 预期结果应该是：", "- [ ] 验证结论：pass / fail / partial")
        }
        "zh-cn:templates/releases/RELEASE-template.md" {
            $markers = @("## Release Checks", "## 下一步选项", "- [ ] CI checks：", "- [ ] 推荐下一步：")
        }
    }

    if (-not (Test-Path -LiteralPath $absolutePath)) {
        return
    }

    $raw = Get-Content -LiteralPath $absolutePath -Raw
    foreach ($marker in $markers) {
        if (-not $raw.Contains($marker)) {
            $contractFailures.Add("$RelativePath is missing required parser-contract marker: $marker")
        }
    }
}

foreach ($relativePath in $requiredPaths) {
    $absolutePath = Join-Path $Root $relativePath
    if (Test-Path -LiteralPath $absolutePath) {
        Write-Output "[PASS] $relativePath"
    } else {
        $missing.Add($relativePath)
        Write-Output "[FAIL] $relativePath"
    }
}

$docsToScan = @(
    "docs\project-brief.md",
    "docs\process.md",
    "docs\architecture.md",
    "docs\testing.md",
    "docs\git-workflow.md",
    "docs\progress.md"
)

foreach ($relativePath in $docsToScan) {
    $absolutePath = Join-Path $Root $relativePath
    if (-not (Test-Path -LiteralPath $absolutePath)) {
        continue
    }
    $content = Get-Content -LiteralPath $absolutePath
    foreach ($pattern in $placeholderPatterns) {
        if ($content | Where-Object { $_ -match $pattern }) {
            $warnings.Add("$relativePath contains placeholder-like text: $pattern")
        }
    }
}

foreach ($relativePath in @("templates\tasks\TASK-template.md", "templates\tasks\SUBTASK-template.md", "templates\evidence\EVIDENCE-000-template.md")) {
    Test-TemplateContract -RelativePath $relativePath
}
if ($workflowProfile -eq "full") {
    Test-TemplateContract -RelativePath "templates\releases\RELEASE-template.md"
}

$evidenceFiles = Get-ChildItem -Path (Join-Path $Root "evidence\records") -Filter "EVIDENCE-*.md" -File -ErrorAction SilentlyContinue
if (-not $evidenceFiles) {
    $warnings.Add("No evidence files found under evidence/records/")
}

$concreteTasks = Get-ChildItem -Path (Join-Path $Root "tasks\active") -Filter "TASK-*.md" -File -ErrorAction SilentlyContinue
if (-not $concreteTasks) {
    $warnings.Add("No concrete task cards found under tasks/active/")
}

foreach ($task in $concreteTasks) {
    $raw = Get-Content -LiteralPath $task.FullName -Raw
    $parallel = ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?decomposition decision:\s*parallel_subtasks\s*$") -or
        ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?parallelization candidate:\s*yes\s*$") -or
        ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?拆分决策[:：]\s*parallel_subtasks\s*$")
    $hasSubtaskLink = $raw -match "(?im)tasks/(?:active/)?SUBTASK-\d{3}.*\.md"
    if ($parallel -and -not $hasSubtaskLink) {
        $warnings.Add("$($task.Name) is marked for parallel work but does not link any subtasks")
    }
}

if ($taskCompletionGitMode -notin @("manual", "auto")) {
    $warnings.Add("workflow-config.env has unknown TASK_COMPLETION_GIT_MODE=$taskCompletionGitMode; use manual or auto")
}
if ($hotStateMode -notin @("branch-aware", "task-aware")) {
    $warnings.Add("workflow-config.env has unknown HOT_STATE_MODE=$hotStateMode; use branch-aware or task-aware")
}
if ($externalIssueSource -notin @("none", "github", "jira", "linear")) {
    $warnings.Add("workflow-config.env has unknown EXTERNAL_ISSUE_SOURCE=$externalIssueSource; use none, github, jira, or linear")
}
if ($connectorMode -ne "pull-only") {
    $warnings.Add("workflow-config.env has unknown CONNECTOR_MODE=$connectorMode; use pull-only")
}

$taskFiles = @()
$taskFiles += @(Get-ChildItem -Path (Join-Path $Root "tasks\active") -Filter "TASK-*.md" -File -ErrorAction SilentlyContinue)
$taskFiles += @(Get-ChildItem -Path (Join-Path $Root "tasks\active") -Filter "SUBTASK-*.md" -File -ErrorAction SilentlyContinue)
$taskFiles += @(Get-ChildItem -Path (Join-Path $Root "tasks\history") -Filter "*.md" -File -ErrorAction SilentlyContinue)
foreach ($task in $taskFiles) {
    if (Test-CompletedTaskFile -Path $task) {
        $raw = Get-Content -LiteralPath $task.FullName -Raw
        if ($taskCompletionGitMode -eq "auto") {
            if (-not (Test-AutoGitClosure -Raw $raw)) {
                $warnings.Add("$($task.Name) appears complete but does not record committed Git closure with commit hash or message")
            }
        } else {
            if (-not (Test-ManualGitClosure -Raw $raw)) {
                $warnings.Add("$($task.Name) appears complete but does not record manual Git closure: commit status not committed, uncommitted reason, and recommended commit message")
            }
        }
    }
}

if (-not (Test-NextStepSignal -RootPath $Root)) {
    $warnings.Add("docs\progress.md does not contain a concrete next-step signal; before archiving work, add a recommended next step, a full-profile backlog item, a waiting user decision, or a terminal reason")
}

if ($contractFailures.Count -gt 0) {
    Write-Output ""
    Write-Output "Contract Failures:"
    foreach ($failure in $contractFailures) {
        Write-Output "[FAIL] $failure"
    }
}

if ($warnings.Count -gt 0) {
    Write-Output ""
    Write-Output "Warnings:"
    foreach ($warning in $warnings) {
        Write-Output "[WARN] $warning"
    }
}

Write-Output ""
if ($missing.Count -eq 0 -and $contractFailures.Count -eq 0) {
    Write-Output "Result: PASS"
} else {
    Write-Output "Result: FAIL"
}

if ($Strict -and (($missing.Count -gt 0) -or ($contractFailures.Count -gt 0))) {
    exit 1
}
