# Generated by codex-sdd-workflow. Upgrade via the skill, not by manual copy from a different repo.
param(
    [string]$Root = "",
    [switch]$Strict
)

if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

$configPath = Join-Path $Root "workflow-config.env"
$rootShimsEnabled = $true
$workflowProfile = "lite"
$taskCompletionGitMode = "manual"
if (Test-Path -LiteralPath $configPath) {
    foreach ($line in Get-Content -LiteralPath $configPath) {
        if ($line -match "^\s*ROOT_SHIMS=(.+?)\s*$") {
            $rootShimsEnabled = $matches[1].Trim() -ne "disabled"
        }
        if ($line -match "^\s*WORKFLOW_PROFILE=(.+?)\s*$") {
            $workflowProfile = $matches[1].Trim()
        }
        if ($line -match "^\s*TASK_COMPLETION_GIT_MODE=(.+?)\s*$") {
            $taskCompletionGitMode = $matches[1].Trim()
        }
    }
}

$requiredPaths = @(
    "workflow-config.env",
    "README.md",
    "workflow.md",
    "docs\project-brief.md",
    "docs\process.md",
    "docs\architecture.md",
    "docs\testing.md",
    "docs\git-workflow.md",
    "docs\progress.md",
    "docs\workflow-audit.md",
    "tasks\active",
    "tasks\history",
    "templates\README.md",
    "templates\tasks\TASK-template.md",
    "templates\tasks\SUBTASK-template.md",
    "templates\adr\ADR-000-template.md",
    "templates\evidence\EVIDENCE-000-template.md",
    "adr\README.md",
    "adr\records",
    "scripts\new-task.ps1",
    "scripts\new-task.sh",
    "scripts\new-subtask.ps1",
    "scripts\new-subtask.sh",
    "scripts\new-adr.ps1",
    "scripts\new-adr.sh",
    "scripts\archive-task.ps1",
    "scripts\archive-task.sh",
    "scripts\session-brief.ps1",
    "scripts\session-brief.sh",
    "scripts\validate-sdd.ps1",
    "scripts\validate-sdd.sh",
    "scripts\handoff-template.ps1",
    "scripts\handoff-template.sh",
    "evidence\README.md"
)

if ($rootShimsEnabled) {
    $requiredPaths = @("..\AGENTS.md", "..\README.md") + $requiredPaths
}

if ($workflowProfile -eq "full") {
    $requiredPaths += @(
        "docs\agile-delivery.md",
        "docs\ci-cd.md",
        "backlog\README.md",
        "backlog\items",
        "sprints\README.md",
        "sprints\active",
        "sprints\history",
        "releases\README.md",
        "releases\records",
        "automation\README.md",
        "automation\github-actions\ci.yml.example",
        "templates\backlog\BACKLOG-ITEM-template.md",
        "templates\sprints\SPRINT-template.md",
        "templates\releases\RELEASE-template.md",
        "scripts\new-backlog-item.ps1",
        "scripts\new-backlog-item.sh",
        "scripts\new-sprint.ps1",
        "scripts\new-sprint.sh",
        "scripts\new-release.ps1",
        "scripts\new-release.sh"
    )
}

$legacyActiveTaskLabel = "活跃" + "任务"
$placeholderPatterns = @(
    "^\s*-\s*\[\s\]\s*一句话总结已填写\s*$",
    "^\s*-\s*\[\s\]\s*用一句话描述这个产品或系统：\s*$",
    "^\s*-\s*\[\s\]\s*这个项目要解决什么痛点？\s*$",
    "^\s*-\s*\[\s\]\s*目标 1：\s*$",
    "^\s*-\s*\[\s\]\s*项目状态：\s*$",
    "^\s*-\s*\[\s\]\s*$([regex]::Escape($legacyActiveTaskLabel))：\s*$",
    "^\s*-\s*\[\s\]\s*当前 active task：`tasks/active/TASK-XXX-sample\.md`\s*$",
    "^\s*-\s*\[\s\]\s*当前主题：\s*$",
    "^\s*-\s*\[\s\]\s*问题：\s*$",
    "^\s*-\s*\[\s\]\s*拆分状态：\s*$",
    "^\s*Describe the product or system in one sentence\.\s*$",
    "^\s*-\s*What pain does this project solve\?\s*$",
    "^\s*-\s*Goal 1:\s*$",
    "^\s*-\s*project state:\s*$",
    "^\s*-\s*active task:\s*$",
    "^\s*-\s*Question:\s*$",
    "^\s*-\s*decomposition status:\s*$"
)

$missing = New-Object System.Collections.Generic.List[string]
$warnings = New-Object System.Collections.Generic.List[string]

function Test-NextStepSignal {
    param([string]$RootPath)

    $progressPath = Join-Path $RootPath "docs\progress.md"
    if (-not (Test-Path -LiteralPath $progressPath)) {
        return $false
    }

    foreach ($line in Get-Content -LiteralPath $progressPath) {
        $normalized = $line -replace "^\s*-\s*(?:\[[ xX]\]\s*)?", ""
        if ($normalized -match "^(recommended next step|next active task|backlog item|waiting on user decision|no next step because|推荐下一步|下一步 active task|backlog 条目|等待用户决策|无需下一步原因)[:：]\s*(\S.*)$") {
            $value = $matches[2].Trim()
            if ($value -notmatch "^(none|n/a|N/A|无)$" -and $value -notmatch "(TASK-XXX|BACKLOG-XXX|sample)") {
                return $true
            }
        }
    }

    return $false
}

function Test-CompletedTaskFile {
    param([System.IO.FileInfo]$Path)

    $historyDir = [System.IO.Path]::GetFullPath((Join-Path $Root "tasks\history")).TrimEnd('\', '/')
    $taskPath = [System.IO.Path]::GetFullPath($Path.FullName)
    if ($taskPath.StartsWith("$historyDir\", [System.StringComparison]::OrdinalIgnoreCase)) {
        return $true
    }

    $raw = Get-Content -LiteralPath $Path.FullName -Raw
    return ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?(status|commit status):\s*(done|complete|committed|已完成|已提交)\s*$") -or
        ($raw -match "(?im)^-\s*\[[xX]\]\s*(done|complete|committed|已完成|已提交)\s*$") -or
        ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?(done|complete)\s*$")
}

function Test-ManualGitClosure {
    param([string]$Raw)

    return ($Raw -match "(?im)commit status[:：]\s*(not committed|未提交)") -and
        ($Raw -match "(?im)(uncommitted reason|未提交原因)[:：]\s*\S") -and
        ($Raw -match "(?im)(recommended commit message|推荐 commit message)[:：]\s*\S")
}

function Test-AutoGitClosure {
    param([string]$Raw)

    return ($Raw -match "(?im)commit status[:：]\s*(committed|已提交)") -and
        ($Raw -match "(?im)(commit hash|commit message|recommended commit message|推荐 commit message)[:：]\s*\S")
}

foreach ($relativePath in $requiredPaths) {
    $absolutePath = Join-Path $Root $relativePath
    if (Test-Path -LiteralPath $absolutePath) {
        Write-Output "[通过] $relativePath"
    } else {
        $missing.Add($relativePath)
        Write-Output "[缺失] $relativePath"
    }
}

$docsToScan = @(
    "docs\project-brief.md",
    "docs\process.md",
    "docs\architecture.md",
    "docs\testing.md",
    "docs\git-workflow.md",
    "docs\progress.md"
)

foreach ($relativePath in $docsToScan) {
    $absolutePath = Join-Path $Root $relativePath
    if (-not (Test-Path -LiteralPath $absolutePath)) {
        continue
    }
    $content = Get-Content -LiteralPath $absolutePath
    foreach ($pattern in $placeholderPatterns) {
        if ($content | Where-Object { $_ -match $pattern }) {
            $warnings.Add("$relativePath 仍包含占位内容: $pattern")
        }
    }
}

$evidenceFiles = Get-ChildItem -Path (Join-Path $Root "evidence\records") -Filter "EVIDENCE-*.md" -File -ErrorAction SilentlyContinue
if (-not $evidenceFiles) {
    $warnings.Add("evidence/records 下还没有真实 evidence 文件")
}

$concreteTasks = Get-ChildItem -Path (Join-Path $Root "tasks\active") -Filter "TASK-*.md" -File -ErrorAction SilentlyContinue
if (-not $concreteTasks) {
    $warnings.Add("tasks/active 下还没有真实 task card")
}

foreach ($task in $concreteTasks) {
    $raw = Get-Content -LiteralPath $task.FullName -Raw
    $parallel = ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?拆分决策：\s*parallel_subtasks\s*$") -or ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?是否适合并行：\s*yes\s*$") -or ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?decomposition decision:\s*parallel_subtasks\s*$") -or ($raw -match "(?im)^-\s*(?:\[[ xX]\]\s*)?parallelization candidate:\s*yes\s*$")
    $hasSubtaskLink = $raw -match "(?im)tasks/(?:active/)?SUBTASK-\d{3}.*\.md"
    if ($parallel -and -not $hasSubtaskLink) {
        $warnings.Add("$($task.Name) 被标记为并行任务，但没有链接任何 subtask")
    }
}

if ($taskCompletionGitMode -notin @("manual", "auto")) {
    $warnings.Add("workflow-config.env 中的 TASK_COMPLETION_GIT_MODE=$taskCompletionGitMode 无法识别；请使用 manual 或 auto")
}

$taskFiles = @()
$taskFiles += @(Get-ChildItem -Path (Join-Path $Root "tasks\active") -Filter "TASK-*.md" -File -ErrorAction SilentlyContinue)
$taskFiles += @(Get-ChildItem -Path (Join-Path $Root "tasks\active") -Filter "SUBTASK-*.md" -File -ErrorAction SilentlyContinue)
$taskFiles += @(Get-ChildItem -Path (Join-Path $Root "tasks\history") -Filter "*.md" -File -ErrorAction SilentlyContinue)
foreach ($task in $taskFiles) {
    if (Test-CompletedTaskFile -Path $task) {
        $raw = Get-Content -LiteralPath $task.FullName -Raw
        if ($taskCompletionGitMode -eq "auto") {
            if (-not (Test-AutoGitClosure -Raw $raw)) {
                $warnings.Add("$($task.Name) 看起来已完成，但没有记录已提交的 Git handoff、commit hash 或 commit message")
            }
        } else {
            if (-not (Test-ManualGitClosure -Raw $raw)) {
                $warnings.Add("$($task.Name) 看起来已完成，但没有记录 manual Git handoff：commit status 未提交、未提交原因和推荐 commit message")
            }
        }
    }
}

if (-not (Test-NextStepSignal -RootPath $Root)) {
    $warnings.Add("docs\progress.md 还没有具体下一步信号；归档前请补充下一步 active task、下一步选项推荐、full profile backlog 条目、等待用户决策，或终态原因")
}

if ($warnings.Count -gt 0) {
    Write-Output ""
    Write-Output "警告："
    foreach ($warning in $warnings) {
        Write-Output "[警告] $warning"
    }
}

Write-Output ""
if ($missing.Count -eq 0) {
    Write-Output "结果: 通过"
} else {
    Write-Output "结果: 失败"
}

if ($Strict -and ($missing.Count -gt 0)) {
    exit 1
}
